services:

  web:
    build: .
    container_name: springboot-web

    ports:
      - "8080:80"
      - "2222:22"

    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    container_name: mysql-db

    environment:
      MYSQL_ROOT_PASSWORD: Hello@123
      MYSQL_DATABASE: bun_sengleang-db

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: