spring.datasource.url=jdbc:mysql://localhost:3306/football_rental_db
spring.datasource.username=football
spring.datasource.password=football123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true